-- Modify the data model for question and answer

--ADAPT THE QUESTIONS
ALTER TABLE  QUESTION
ADD QUESTION_TYPE INTEGER DEFAULT 0;
ALTER TABLE  QUESTION
ADD NUMERO INTEGER DEFAULT 0;
ALTER TABLE  QUESTION
ADD PICTURE BYTEA NULL;

--ADAPT THE ANSWERS 
ALTER TABLE  ANSWER
ADD NUMERO INTEGER DEFAULT 0;
ALTER TABLE  ANSWER
ADD DATA TEXT;
ALTER TABLE  ANSWER
ADD PICTURE BYTEA NULL;
ALTER TABLE  ANSWER
DROP COLUMN IS_TRUE;

-- CREATE A CATEGORY FOR ANSWERS
CREATE TABLE ANSWER_CATEGORY(
    ID SERIAL PRIMARY KEY,
    QUESTION_ID INTEGER NOT NULL,
    NUMERO INTEGER  DEFAULT 0,
    NAME VARCHAR(150),
    TIMESTAMPS TIMESTAMP,
    CONSTRAINT FK_CATEGORY_QUESTION_ID FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION (ID)
);
