-- add languages column for courses
ALTER TABLE  COURSE
ADD LANGUAGE VARCHAR(150);

-- delete unused tables
DROP TABLE IF EXISTS MISSION CASCADE;
DROP TABLE IF EXISTS AWARD CASCADE;
DROP TABLE IF EXISTS TRAVEL CASCADE;
DROP TABLE IF EXISTS TRANSPORT CASCADE;