ALTER TABLE CHALLENGE
DROP COLUMN  TEAM_ENABLED;

ALTER TABLE CHALLENGE
ADD TEAM_ENABLED BOOLEAN DEFAULT FALSE;

ALTER TABLE CHALLENGE_VOTE
DROP COLUMN  CHALLENGE_ID;

ALTER TABLE CHALLENGE_VOTE
DROP COLUMN  SCORE;

ALTER TABLE CHALLENGE_VOTE
ADD PARTICIPATION_ID INTEGER NOT NULL;

ALTER TABLE CHALLENGE_VOTE
ADD CONSTRAINT FK__CHALLENGE_VOTE_PARTICIPATION_ID FOREIGN KEY (PARTICIPATION_ID) REFERENCES PARTICIPATION (ID);