ALTER TABLE PROFILE
DROP COLUMN  SESSION_TOKEN;

ALTER TABLE PROFILE
DROP COLUMN  PASSWORD;

ALTER TABLE PROFILE
DROP COLUMN  IS_ADMIN;

-- une session en base de données pour securiser les access
CREATE TABLE USER_ACCOUNT (
    ID SERIAL PRIMARY KEY,
    PASSWORD  VARCHAR(250) NOT NULL,
    TOKEN  VARCHAR(250) DEFAULT NULL,
    IS_ADMIN BOOLEAN DEFAULT FALSE,
    TIMESTAMPS TIMESTAMP
);

DELETE FROM PROFILE AS p WHERE (p.MAIL = 'admin@sustainapp.ca');

ALTER TABLE PROFILE
ADD USER_ACCOUNT_ID INTEGER NOT NULL;

ALTER TABLE PROFILE
ADD CONSTRAINT FK__PROFILE_USER_ACCOUNT_ID FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT (ID);